import Header from "../component/header";
import data from "../component/data.json";
import Head from "next/head";

export default function Education() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="main">
        <div className="grid">
          {data.data.map((d) =>
            d.diplomes.map((e) => (
              <a href={e.slug} className="card">
                <h2>{e.name}&rarr;</h2>
                <p>{e.ecole}</p>
                <p>{e.date}</p>
                <p>{e.description}</p>
              </a>
            ))
          )}
        </div>
      </main>
    </div>
  );
}
