import Head from "next/head";
import data from "../component/data.json";
import Header from "../component/header";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.data.map((d) => (
        <>
          <Header />
          <main className="main">
            <div>Présentation</div>
            <div className="grid">
              <a href="/projets" className="card">
                <h2>Projets &rarr;</h2>
                <p>Find in-depth information about Next.js features and API.</p>
              </a>

              <a href="/experiences" className="card">
                <h2>Expériences &rarr;</h2>
                <p>
                  Learn about Next.js in an interactive course with quizzes!
                </p>
              </a>

              <a href="/education" className="card">
                <h2>Éducation &rarr;</h2>
                <p>Discover and deploy boilerplate example Next.js projects.</p>
              </a>

              <a
                href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
                className="card"
              >
                <h2>Intérêts &rarr;</h2>
                <p>
                  Instantly deploy your Next.js site to a public URL with
                  Vercel.
                </p>
              </a>
            </div>
          </main>

          <footer className="footer">
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{" "}
              {d.coordonnees.map((c) => (
                <span>
                  {c.nom} {c.prenom}
                </span>
              ))}
            </a>
          </footer>
        </>
      ))}
    </div>
  );
}
