import Header from "../component/header";
import data from "../component/data.json";
import Head from "next/head";

export default function Projets() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="main">
        <div className="grid">
          {data.data.map((d) =>
            d.projets.map((p) => (
              <a href={p.slug} className="card">
                <h2>{p.name}&rarr;</h2>
                <p>{p.date}</p>
                <p>{p.description}</p>
                <p>Résultats :</p>
                <ul>
                  {p.resultats.map((r) => (
                    <li>{r.resultat}</li>
                  ))}
                </ul>
              </a>
            ))
          )}
        </div>
      </main>
    </div>
  );
}
